export const WORK_EXPERIENCE = [
  {
    company: 'Cognizant Softvision',
    role: 'Frontend Developer',
    dateStart: 'Jan 2023',
    dateEnd: 'present',
    location: 'Bucharest',
    companyLogo: 'cognizant',
    projects: [
      {
        name: 'Client 1',
        country: 'Belgium',
        startDate: 'Mar 2023',
        endDate: 'present',
        industry: ['Banking'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'Sass',
          'TypeScript',
          'REST',
          'RxJs',
          'Mocha',
          'Postman',
          'Chai.js',
        ],
        contribution: [
          'Internal web application for fraud monitoring, implemented using an internal component framework.',
        ],
      },
    ],
  },
  {
    company: 'Deloitte Digital',
    role: 'Consultant / FE Developer',
    dateStart: 'Oct 2021',
    dateEnd: 'Dec 2022',
    location: 'Bucharest',
    companyLogo: 'deloitte-digital',
    projects: [
      {
        name: 'Client 1 - Alpha Team',
        country: 'United Kingdom',
        startDate: 'Oct 2021',
        endDate: 'Jan 2022',
        industry: ['Banking', 'Insurance'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'RxJs',
          'Jira',
          'moment.js',
          'Postman',
          'Sass',
        ],
        contribution: [
          'Internal banking application used by agents which helps them to check a client insurance policies.',
          'Delivered different features: feature that show to the user the active policies into a responsive and interactive design, the possibility of a Mid Term Adjustment to a policy.',
        ],
      },
      {
        name: 'Client 2',
        country: 'Germany',
        startDate: 'Feb 2022',
        endDate: 'Dec 2022',
        industry: ['Banking'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'React.js',
          'Thymeleaf',
          'Mambu',
          'moment.js',
          'TypeScript',
          'AWS Services',
          'Java',
          'Docker',
          'Postman',
          'Sass',
          'Next.js',
        ],
        contribution: [
          'Internal banking application used by agents which helps them to check a client profile, create loan accounts, refinance loans, update details and create new client accounts.',
          'Modified Java code accordingly to Thymeleaf templates to create custom PDF files and uploaded custom applications as modules in a Mambu interface.',
        ],
      },
    ],
  },
  {
    company: 'IBM iX',
    role: 'Frontend Developer',
    dateStart: 'Dec 2018',
    dateEnd: 'Oct 2021',
    location: 'Bucharest',
    companyLogo: 'ibm',
    projects: [
      {
        name: 'Internship',
        country: 'Romania',
        startDate: 'Dec 2018',
        endDate: 'Feb 2019',
        industry: [],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'RxJs',
          'Vue.js',
          'Vuex',
          'Firebase',
          'Ionic',
          'Photoshop',
          'Postman',
          'Sass',
        ],
        contribution: [
          'Designing mobile-based features, working in an agile team.',
        ],
      },
      {
        name: 'Client 1',
        country: 'Germany',
        startDate: 'Mar 2019',
        endDate: 'Mar 2020',
        industry: ['Insurance'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'Ionic',
          'Sass',
          'TypeScript',
          'REST',
          'Capacitor',
          'RxJs',
          'Postman',
          'SharePoint',
          'Slack',
        ],
        contribution: [
          "Development of internal applications both locally and at the client's premises: application for monitoring the security of devices used within the company, application for synthesizing information held by the company and used by its staff, application used by staff performing repairs at the client's premises according to the insurance held.",
        ],
      },
      {
        name: 'Client 2',
        country: 'United Kingdom',
        startDate: 'Mar 2020',
        endDate: 'Mar 2020',
        industry: ['Retail'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'React.js',
          'GraphQL',
          'Slack',
        ],
        contribution: [
          'Redesigned flow for buying recyclable materials for a retailer.',
        ],
      },
      {
        name: 'Client 3',
        country: 'United States',
        startDate: 'Apr 2020',
        endDate: 'Oct 2021',
        industry: ['E-Commerce'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'Sass',
          'TypeScript',
          'REST',
          'RxJs',
          'Adobe Experience Manager',
          'Virtualbox',
          'JQuery',
          'Mocha',
          'Postman',
          'Chai.js',
          'Confluence',
          'Jira',
          'AWS Services',
          'GitHub',
          'Bash',
        ],
        contribution: [
          'Being part of the team in a micro frontend team, delivering shopping list, product pages and cart functionalities.',
          'Delivered multiple features, including: feature to improve the customer experience regarding the promotional codes and feature to help customers to find easier the products already bought in the past.',
        ],
      },
    ],
  },
  {
    company: 'Groupe Renault',
    role: 'Database Administrator',
    dateStart: 'Jun 2017',
    dateEnd: 'Sep 2017',
    location: 'Bucharest',
    companyLogo: 'renault',
    projects: [
      {
        name: 'Drive your future',
        country: 'Worldwide',
        startDate: 'Jun 2017',
        endDate: 'Sep 2017',
        industry: ['Automotive'],
        technologies: ['Matlab', 'SQL', 'Excel', 'PowerPoint', 'SharePoint'],
        contribution: [
          'Generating statistics on the use of their machines, according to data received from the research team.',
        ],
      },
    ],
  },
];
