import { Certification } from 'src/app/interfaces/certification';
import { Testimonial } from 'src/app/interfaces/testimonial';

// Summary
export const SOCIAL_LINKS = {
  EMAIL: 'madalinaeleonora.gheorghe@gmail.com',
  LINKEDIN: 'https://www.linkedin.com/in/madalinaeleonorag/',
  MEDIUM: 'https://madalinaeleonorag.medium.com/',
  GITHUB: 'https://github.com/madalinaeleonorag',
  INSTAGRAM: 'https://www.instagram.com/madalinaeleonorag/',
  FACEBOOK: 'https://www.facebook.com/mdx.madalinaeleonora/',
  PAYPAL: 'https://www.paypal.com/paypalme/madalinaeleonorag',
  PX500: 'https://500px.com/p/madalinaeleonorag?view=galleries',
  SHUTTERSTOCK: 'https://www.shutterstock.com/g/Madalina-Eleonora',
};

export const COPYRIGHT = '© Madalina-Eleonora Gheorghe 2023';

// Descriptions
export const SUMMARY = `I am a senior Frontend Developer with a long experience working with Angular and RxJs.
  Additional, I have experience working with React.js, Sass, AWS Services and Azure.
  Currently working for <a target="_blank" href="https://www.cognizantsoftvision.com/">Cognizant Softvision</a>, former Frontend Application Developer at <a target="_blank" href="https://ro.deloittedigital.com/">Deloitte Digital</a>, Frontend Developer at <a target="_blank" href="https://www.ibm.com/services/ibmix">IBM iX</a> and Database Administrator at <a target="_blank" href="https://www.renaultgroup.com/en/">Groupe Renault</a>.
  I delivered unique features in the past projects, improving user experience, contributing actively in meetings with suggestions and helping other colleagues, maintaining a good communication with the client.
  I worked with large companies, in industries like banking, insurance, retail and e-commerce.
  My studies were based in Information Technology Administration and Management, having a bachelor and a master degree from <a target="_blank" href="https://www.rau.ro/">Romanian-American University</a>.`;

// TESTIOMNIALS
export const TESTIOMNIALS: Testimonial[] = [
  {
    text: `Madalina is really valuable member,
      more of self-initiative in areas which are visibly not covered well on project will help her to present herself with higher seniority,
      she is currently operating at the next level.`,
    author: 'Pavol Tomek',
    role: 'Project Manager / Scrum Master',
    date: 'Nov 10, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `She proves her great technical expertise and collaboration skills with every task that is assigned to her, and is supporting the project teams with business and technical information for successful integrations.`,
    author: 'Cristina-Mihaela Antohe',
    role: 'Senior Consultant',
    date: 'Nov 7, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `She tackled new features with ease, always on time and with the highest possible quality. She’s a vocal team member and she’s alway deeply involved in discovering all the requirements of what she needs to implement. Madalina’s strong commitment to having all the details in has been helping the team get a better understanding of the tasks. I’m confident that she can provide people with the support needed to get the job done.`,
    author: 'Andrei-Ioan Popescu',
    role: 'Team Lead',
    date: 'Oct 19, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `Feedback from both team and local technical lead is positive as Madalina started working on the project near stabilization phase, but managed to get familiar in a short timeframe with the complexity of the project.`,
    author: 'Silvana-Roberta Helal',
    role: 'Senior Manager',
    date: 'May 2, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `Madalina could quickly take over the tasks assigned to her and she could deliver them with a very good quality on the agreed time. Madalina is also a team player and she knows when she need to raise the hand when and issue appears. I suggest Madalina to continue working on this way and not stop learning not only frontend technical things but also Cloud and Devops tools to increase the value of her profile.`,
    author: 'Diego Frison Aladren',
    role: 'Solution Lead',
    date: 'Apr 20, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `From early on, she was fully independent from a tech perspective, requiring assistance only for understanding the feature she needed to implement. Even though she is a less experienced frontend developer than the former one, seeing her work I can confirm that she managed to surpass everyone’s expectations. She communicates the blockers & issues clearly, she developed complex features faster and with increased quality than before.She handled cloud configuration & installs for the applications that she developed with ease, even though this is out of her area of expertise. She is asking everyone for information when she needs it, she is efficiently communicating her concerns and thus, every story that she implemented was easily integrated with the backend components and the platform. Moreover, I appreciate the fact that during refinements and clarifications, she challenges the approach and the input data, and, thus we managed to increase the quality of the features’ description resulting in better structured stories and acceptance criteria. I’m happy that I got the chance to work with her and I would definitely like to continue doing this in the future.`,
    author: 'Andrei-Ioan Popescu',
    role: 'Team Lead',
    date: 'Apr 20, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `Overnight she became the expert and point of contact for front-end applications. She has delivered all her tasks with great speed and took on several topics instantly. The entire project is happy to have her onboard.`,
    author: 'Kavitha Padmanabham',
    role: 'Business Analyst',
    date: 'Apr 20, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `Madalina instantly collaborated with the team and importantly understood our objectives quickly. The repeated feedback from the development lead was how quickly our production increased – thanks to Madalina. Madalina clearly has a strong skillset which benefited our FE team significantly. Madalina worked hard to develop her colleagues and ensured they were implementing best practice techniques.`,
    author: 'Jack Taylor',
    role: 'Manager',
    date: 'Apr 6, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `During her time spent on Alpha space, Madalina has shown a lot of flexibility and maturity. Even though she had to change teams and industries, from banking to insurance, her experience has been extremely appreciate by our main stakeholders and there have been multiple requests to keep her on Alpha. From a technical perspective, she delivers extremely fast and at a high quality. For example, she managed to bring visible improvements on the web app in just a couple of weeks, as well as mentioning more junior team members. If given the opportunity (to match her expertise and role desired), she has the ability to make a huge difference, she has the skills and determination needed.`,
    author: 'Isabela Pecete',
    role: 'Project Manager',
    date: 'Feb 7, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: `She gave a huge boost to our Web app development, she came with a very long list of improvements to our existing app and managed to implement a lot of those items in just a couple of weeks. The quality of the code she has been writing and the overall work quality has been impressive. I would always want her in my team, given the opportunity.`,
    author: 'Dragos-Vasile Lungu',
    role: 'Technical Lead',
    date: 'Ian 28, 2022',
    from: 'Deloitte Digital',
  },
  {
    text: "She's ambitious, enjoys learning new things all the time, she takes action whenever the situation requires it.She never stepped back from a challenge, but rather is determined to figure out how we overcome it.Madalina was there when anyone from the team needed support on any level: if it's a coding problem, providing some information, investigating an issue, giving an advice non-work related or just for a simple talk. She always encourages everyone to push their limits and become a better version on themselves. Her patient and professional attitude makes it really easy to talk to. She's not just about work, she's also about being human and having a good time while trying to grow as much as possible.",
    author: 'Narcisa-Elena Badea',
    role: 'Frontend Developer',
    date: 'Nov 27, 2021',
    from: 'IBM',
  },
  {
    text: "Madalina is a very practical person. Working on various projects with her I was able to see how flexible she can be, especially with the help of her vast knowledge in the IT field. In addition to intelligence, I noticed that she also has leadership qualities that have been very helpful in any project. Attention to detail characterizes her, so it's hard not to get things going almost perfectly with her. She is a charismatic, dynamic person with a very precise decision-making power. Nothing remains unresolved with Madalina!",
    author: 'Mihaela Gales',
    role: 'System Support Engineer',
    date: 'Nov 25, 2021',
    from: 'Vodafone',
  },
  {
    text: "For the past years I had the opportunity to work along Madalina on multiple personal & comercial projects. She was able to develop features in an extremely elegant and creative way all the time. Her ability to develop high quality products while being under extreme pressure is something that I look up to, not only that she's able to stay calm and professional in difficult situations.She's also able to make everyone in the team feel that they are also capable of doing more than they expect from themselves.",
    author: 'Emanuel Cepoi',
    role: 'Full-Stack Developer',
    date: 'Sep 24, 2021',
    from: 'Wooter Apparel',
  },
  {
    text: 'Madalina is always reliable and helping her team members, able to understand the requirements and come up with a solution. It was a joy and always had confidence while working with her. I am strongly recommend her in any new opportunity and challenge.',
    author: 'Raluca Rusu',
    role: 'Project Manager',
    date: 'Sep 13, 2021',
    from: 'IBM',
  },
  {
    text: 'Madalina was my mentor during my internship period at IBM iX. She was friendly and open from the start and rapidly developed a learning plan for me. We had a great mentor-mentee relationship during that time and she was always eager to show me new front-end tricks and quirks. The proactivity which she possesses inspired me a lot throught my internship period.',
    author: 'Madalin Tuca',
    role: 'Frontend Developer',
    date: 'Sep 2, 2021',
    from: 'IBM',
  },
  {
    text: 'Appreciate your guidance and helping bring new talent to our wider iX IBM team and also constant strong contribution to our project delivery. Keep up the good work!',
    author: 'Alexandra-Luminita Tanef',
    role: 'Project Manager',
    date: 'Aug 6, 2021',
    from: 'IBM',
  },
  {
    text: "She quickly managed to learn and acquire quite an extensive set of skills.Her determination to never give up and always learn and improve, is what sets her apart from many other developers out there.It's been a pleasure working with her. She is currently riding the proverbial wave and I am sure she will achieve great things in the future.I highly recommend her to anyone looking to expand their team(s).",
    author: 'Theodor Palamaru',
    role: 'Frontend Developer',
    date: 'Jun 22, 2021',
    from: 'IBM',
  },
  {
    text: 'Great job on the project Madalina, the feedback received for the project is very good. Also I like your drive and attitude and I hope you will continue to invest in your skills as you did until now, and more.',
    author: 'Sorina Radulescu',
    role: 'People Manager',
    date: 'Dec 16, 2020',
    from: 'IBM',
  },
  {
    text: 'Madalina had a very good start and path in the project, having in charge a very hard project and client on a team, being in front of the client for direct communication and problem solving. I am very satisfied with her abilities to create and maintain a good working relationship both with the client and her team members,to adapt quickly to change and to help any time need it.',
    author: 'Raluca Rusu',
    role: 'Project Manager',
    date: '15 Feb, 2019',
    from: 'IBM',
  },
];

export const WORK_EXPERIENCE = [
  {
    company: 'Cognizant Softvision',
    role: 'Frontend Developer',
    dateStart: 'Jan 2023',
    dateEnd: 'present',
    location: 'Bucharest',
    companyLogo: 'cognizant',
    projects: [
      {
        name: 'Client 1',
        country: 'Belgium',
        startDate: 'Mar 2023',
        endDate: 'present',
        industry: ['Banking'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'Sass',
          'TypeScript',
          'REST',
          'RxJs',
          'Mocha',
          'Postman',
          'Chai.js',
        ],
        contribution: [
          'Internal web application for fraud monitoring, implemented using an internal component framework.',
        ],
      },
    ],
  },
  {
    company: 'Deloitte Digital',
    role: 'Consultant / FE Developer',
    dateStart: 'Oct 2021',
    dateEnd: 'Dec 2022',
    location: 'Bucharest',
    companyLogo: 'deloitte-digital',
    projects: [
      {
        name: 'Client 1 - Alpha Team',
        country: 'United Kingdom',
        startDate: 'Oct 2021',
        endDate: 'Jan 2022',
        industry: ['Banking', 'Insurance'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'RxJs',
          'Jira',
          'moment.js',
          'Postman',
          'Sass',
        ],
        contribution: [
          'Internal banking application used by agents which helps them to check a client insurance policies.',
          'Delivered different features: feature that show to the user the active policies into a responsive and interactive design, the possibility of a Mid Term Adjustment to a policy.',
        ],
      },
      {
        name: 'Client 2',
        country: 'Germany',
        startDate: 'Feb 2022',
        endDate: 'Dec 2022',
        industry: ['Banking'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'React.js',
          'Thymeleaf',
          'Mambu',
          'moment.js',
          'TypeScript',
          'AWS Services',
          'Java',
          'Docker',
          'Postman',
          'Sass',
          'Next.js',
        ],
        contribution: [
          'Internal banking application used by agents which helps them to check a client profile, create loan accounts, refinance loans, update details and create new client accounts.',
          'Modified Java code accordingly to Thymeleaf templates to create custom PDF files and uploaded custom applications as modules in a Mambu interface.',
        ],
      },
    ],
  },
  {
    company: 'IBM iX',
    role: 'Frontend Developer',
    dateStart: 'Dec 2018',
    dateEnd: 'Oct 2021',
    location: 'Bucharest',
    companyLogo: 'ibm',
    projects: [
      {
        name: 'Internship',
        country: 'Romania',
        startDate: 'Dec 2018',
        endDate: 'Feb 2019',
        industry: [],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'RxJs',
          'Vue.js',
          'Vuex',
          'Firebase',
          'Ionic',
          'Photoshop',
          'Postman',
          'Sass',
        ],
        contribution: [
          'Designing mobile-based features, working in an agile team.',
        ],
      },
      {
        name: 'Client 1',
        country: 'Germany',
        startDate: 'Mar 2019',
        endDate: 'Mar 2020',
        industry: ['Insurance'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'Ionic',
          'Sass',
          'TypeScript',
          'REST',
          'Capacitor',
          'RxJs',
          'Postman',
          'SharePoint',
          'Slack',
        ],
        contribution: [
          "Development of internal applications both locally and at the client's premises: application for monitoring the security of devices used within the company, application for synthesizing information held by the company and used by its staff, application used by staff performing repairs at the client's premises according to the insurance held.",
        ],
      },
      {
        name: 'Client 2',
        country: 'United Kingdom',
        startDate: 'Mar 2020',
        endDate: 'Mar 2020',
        industry: ['Retail'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'React.js',
          'GraphQL',
          'Slack',
        ],
        contribution: [
          'Redesigned flow for buying recyclable materials for a retailer.',
        ],
      },
      {
        name: 'Client 3',
        country: 'United States',
        startDate: 'Apr 2020',
        endDate: 'Oct 2021',
        industry: ['E-Commerce'],
        technologies: [
          'HTML',
          'CSS',
          'JavaScript',
          'Angular',
          'Sass',
          'TypeScript',
          'REST',
          'RxJs',
          'Adobe Experience Manager',
          'Virtualbox',
          'JQuery',
          'Mocha',
          'Postman',
          'Chai.js',
          'Confluence',
          'Jira',
          'AWS Services',
          'GitHub',
          'Bash',
        ],
        contribution: [
          'Being part of the team in a micro frontend team, delivering shopping list, product pages and cart functionalities.',
          'Delivered multiple features, including: feature to improve the customer experience regarding the promotional codes and feature to help customers to find easier the products already bought in the past.',
        ],
      },
    ],
  },
  {
    company: 'Groupe Renault',
    role: 'Database Administrator',
    dateStart: 'Jun 2017',
    dateEnd: 'Sep 2017',
    location: 'Bucharest',
    companyLogo: 'renault',
    projects: [
      {
        name: 'Drive your future',
        country: 'Worldwide',
        startDate: 'Jun 2017',
        endDate: 'Sep 2017',
        industry: ['Automotive'],
        technologies: ['Matlab', 'SQL', 'Excel', 'PowerPoint', 'SharePoint'],
        contribution: [
          'Generating statistics on the use of their machines, according to data received from the research team.',
        ],
      },
    ],
  },
];

export const CERTIFICATIONS: Certification[] = [
  {
    logo: 'Udemy',
    name: 'Agile Fundamentals: Including Scrum & Kanban',
    organization: 'Udemy',
    issueDate: 'Oct 2022',
    url: 'https://www.udemy.com/certificate/UC-e30408dc-436b-467e-9d31-daa12d98ea06/',
  },
  {
    logo: 'HackerRank',
    name: 'Angular Certificate',
    organization: 'HackerRank',
    issueDate: 'Mar 2022',
    url: 'https://www.hackerrank.com/certificates/502d54979ed0',
  },
  {
    logo: 'EF-Standard',
    name: 'English Certificate - C1 Advanced',
    organization: 'EF Standard English Test (EF SET)',
    issueDate: 'Mar 2022',
    url: 'https://www.efset.org/cert/V3b9C2',
  },
  // {
  //   logo: 'Think-like-a-hacker',
  //   name: 'Think like a hacker',
  //   organization: 'IBM',
  //   issueDate: 'Sep 2021',
  //   url: 'https://www.credly.com/badges/2b0b25bd-328e-45c3-8248-85e09c380ef2',
  // },
  // {
  //   logo: 'IBM_Cloud_Essentials',
  //   name: 'IBM Cloud Essentials',
  //   organization: 'IBM',
  //   issueDate: 'Jan 2021',
  //   url: 'https://www.youracclaim.com/badges/26b0884f-9c3a-42f1-be74-6b23c4f6a743',
  // },
  // {
  //   logo: 'Security-_-Privacy-by-Design-Foundational',
  //   name: 'Security and Privacy by Design Foundations',
  //   organization: 'IBM',
  //   issueDate: 'Jan 2021',
  //   url: 'https://www.youracclaim.com/badges/84998ca5-487f-4c61-b1e5-298ec991bb20',
  // },
  // {
  //   logo: 'Watson_and_Cloud_Foundations',
  //   name: 'Watson and Cloud Foundations',
  //   organization: 'IBM',
  //   issueDate: 'Jan 2021',
  //   url: 'https://www.youracclaim.com/badges/11c2db76-b461-4bf9-8a12-9a42663d404f',
  // },
  {
    logo: 'IBM-Mentor',
    name: 'IBM Mentor',
    organization: 'IBM',
    issueDate: 'Dec 2020',
    url: 'https://www.youracclaim.com/badges/841adfea-65df-4a8e-bbe1-267d70cb6a21',
  },
  {
    logo: 'JavaScript-Front-End-Development',
    name: 'JavaScript Frontend Development',
    organization: 'IBM',
    issueDate: 'Dec 2020',
    url: 'https://www.youracclaim.com/badges/b6792b26-e919-4de1-bc24-d4192439aa50',
  },
  {
    logo: 'URA',
    name: 'Licentiate & Master in Computer Science for Business Management',
    organization: 'Romanian-American University',
    issueDate: '2015-2020',
    url: 'https://www.rau.ro',
  },
  // {
  //   logo: 'Badges_v8-07_Practitioner',
  //   name: 'Enterprise Design Thinking Practitioner',
  //   organization: 'IBM',
  //   issueDate: 'Mar 2020',
  //   url: 'https://www.youracclaim.com/badges/f28084ab-7407-4d30-8f84-e612adc40402',
  // },
  // {
  //   logo: 'IBM-Agile-Explorer',
  //   name: 'IBM Agile Explorer',
  //   organization: 'IBM',
  //   issueDate: 'Mar 2020',
  //   url: 'https://www.youracclaim.com/badges/8ed472e8-38c5-42c0-aee7-c1993e9f737f',
  // },
  {
    logo: 'Rau-DevHack',
    name: 'Second place at Rau-DevHack Hackathon',
    organization: 'Romanian-American University',
    issueDate: 'Apr 2019',
    url: 'https://devhack.rau.ro/2019/rezultate.html',
  },
  {
    logo: 'DevHacks',
    name: 'First place at Web&Mobile Challenge at DevHacks',
    organization: 'Catalyst',
    issueDate: 'Nov 2018',
    url: 'https://www.facebook.com/DevTalksRomania/videos/1896310230465604/',
  },
  // {
  //   logo: 'URA',
  //   name: 'Licentiate in Computer/Information Technology Administration and Management',
  //   organization: 'Romanian-American University',
  //   issueDate: '2015-2018',
  //   url: 'https://www.rau.ro',
  // },
];
